name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
          # Exclude heavy raw assets to keep Pages artifact lean
          # These files remain in the repo but are not deployed to Pages
          exclude: |
            photo/**
            video/**
            *.ARW
            *.JPG
            *.PNG
            *.mp4

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
